FROM python:3.7.4-stretch

RUN apt-get -y update

# Google Chrome and ChromeDriver
RUN apt-get install -y chromium chromium-driver

# Japanese font
ENV LANGUAGE ja_JP.UTF-8
ENV LANG ja_JP.UTF-8
RUN apt-get install -y --no-install-recommends locales && \
    locale-gen ja_JP.UTF-8 && \
    apt-get install -y --no-install-recommends fonts-ipafont

# python packages
ADD requirements.txt /tmp
RUN pip install -r /tmp/requirements.txt
